<a href="https://colab.research.google.com/github/guttulaswathi/ml/blob/main/mlassignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Perform arithmetic operations on NumPy arrays.


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.arange(4,7)

c=np.array([8,9,10])
print(a,b,c)
print('addition=',a+b)
print('subtraction=',a-b)
print('multiplication=',c*b)
print('division=',a/c)
print('modulus=',a%c)
d=np.add(a,b)
print("addition using add() method:",d)
print("substraction using substract() method",np.subtract(b,c))
print("multiplication using multiply() method",np.multiply(c,d))
print("division using divide() method",np.divide(a,c))
print("modulus using mod() method",np.mod(b,c))

[1 2 3] [4 5 6] [ 8  9 10]
addition= [5 7 9]
subtraction= [-3 -3 -3]
multiplication= [32 45 60]
division= [0.125      0.22222222 0.3       ]
modulus= [1 2 3]
addition using add() method: [5 7 9]
substraction using substract() method [-4 -4 -4]
multiplication using multiply() method [40 63 90]
division using divide() method [0.125      0.22222222 0.3       ]
modulus using mod() method [4 5 6]


2. Write a script to compute the mean and standard deviation of a NumPy array.

In [ ]:
import numpy as np
a=np.array([10,20,30,40])
print(a)
print("mean=",np.mean(a))
print("standard deviation=",np.std(a))
print("median=",np.median(a))

[10 20 30 40]
mean= 25.0
standard deviation= 11.180339887498949
median= 25.0


3. Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [ ]:
import numpy as np
a=np.arange(10,50,5)
print(a)

[10 15 20 25 30 35 40 45]


4. Reshape the array into a 2x4 matrix.

In [ ]:
import numpy as np
a=np.arange(10,50,5)
print(a)
b=a.reshape(2,4)
print(b)

[10 15 20 25 30 35 40 45]
[[10 15 20 25]
 [30 35 40 45]]


5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):

• Extract the sub-matrix containing the last two rows and first two columns.

• Replace all elements greater than 4 with 0.

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print("last two rows=",arr[1:,:3])
print("first two columns=",arr[0:3,:2])
arr[arr>4]=0
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
last two rows= [[4 5 6]
 [7 8 9]]
first two columns= [[1 2]
 [4 5]
 [7 8]]
[[1 2 3]
 [4 0 0]
 [0 0 0]]


6. Create two 1D arrays:

• a = np.array([1, 2, 3])

• b = np.array([4, 5, 6])

• Perform element-wise addition, multiplication, and division.

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a)
print(b)
print("addition=",a+b)
print("multiplication=",a*b)
print("division=",a/b)
print("addition using add() method:",np.add(a,b))
print("multiplication using multiply() method:",np.multiply(a,b))
print("division using divide() method:",np.divide(a,b))

[1 2 3]
[4 5 6]
addition= [5 7 9]
multiplication= [ 4 10 18]
division= [0.25 0.4  0.5 ]
addition using add() method: [5 7 9]
multiplication using multiply() method: [ 4 10 18]
division using divide() method: [0.25 0.4  0.5 ]


7. Create a random NumPy array of size (4, 4). Compute:

• Mean of each column.

• Maximum value of the entire array.

• Sum of all elements.

In [ ]:
import numpy as np
a=np.random.random((4,4))
print(a)
print("mean of each column=",np.mean(a,axis=0))
print("maximum value of the entire array=",np.max(a))
print("sum of all elements=",np.sum(a))


[[0.94280259 0.19079767 0.50584092 0.8116313 ]
 [0.48662922 0.19769024 0.17408804 0.39604593]
 [0.63165384 0.45596224 0.55802436 0.58623339]
 [0.12981301 0.20456134 0.54183573 0.33368189]]
mean of each column= [0.54772467 0.26225287 0.44494726 0.53189813]
maximum value of the entire array= 0.942802586883222
sum of all elements= 7.147291701763778


8. Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply the result by 2.



In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
c=arr+10
result=c*2
print(result)

[1 2 3 4]
[22 24 26 28]


In [ ]:
9. Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from 1 to 100. Perform the following:
• Extract the second "layer" (i.e., the second 2D array) in the first dimension.
• Extract the first two rows and the last three columns from each "layer."
• Replace all elements divisible by 3 with -1.

In [ ]:
import numpy as np
b=np.random.randint(1,100,(3,4,5))
print(b)
print("secon layer",b[1:2,:])
print("first two rows and last three columns",b[:,:2,-3:])
b[b%3==0]=-1
print(b)

[[[59 64 34 62 42]
  [39 52 97 46  7]
  [21 69 45 16 96]
  [41 24 26 81 11]]

 [[15 47 12 41 56]
  [25  1 65 56  3]
  [ 2 19 88 64 71]
  [61 82 64 25 65]]

 [[22 24 80 51 31]
  [90 23 66 51 13]
  [86 45 83 54 91]
  [28 17 53 11 73]]]
secon layer [[[15 47 12 41 56]
  [25  1 65 56  3]
  [ 2 19 88 64 71]
  [61 82 64 25 65]]]
first two rows and last three columns [[[34 62 42]
  [97 46  7]]

 [[12 41 56]
  [65 56  3]]

 [[80 51 31]
  [66 51 13]]]
[[[59 64 34 62 -1]
  [-1 52 97 46  7]
  [-1 -1 -1 16 -1]
  [41 -1 26 -1 11]]

 [[-1 47 -1 41 56]
  [25  1 65 56 -1]
  [ 2 19 88 64 71]
  [61 82 64 25 65]]

 [[22 -1 80 -1 31]
  [-1 23 -1 -1 13]
  [86 -1 83 -1 91]
  [28 17 53 11 73]]]


10. Work with broadcasting and advanced operations in NumPy.
 Create a NumPy array arr of shape (3, 3) with random integers between  1 and 20. Perform the following:
 • Subtract the mean of each row from its respective elements (row-wise normalization).
 • Create a new array by squaring all the elements in arr.
 • Find the indices of the top 3 maximum values in the entire array.

In [ ]:
import numpy as np
arr=np.random.randint(1,20,(3,3))
print(arr)
print("row-wise normalization",arr-arr.mean(axis=1))
c=[np.sqrt(arr)]
print(b)
flat_indices=np.argsort(arr.flatten())[-3:]
top_3_indices=np.unravel_index(flat_indices,arr.shape)
top_3_indices=list(zip(top_3_indices[0],top_3_indices[1]))
print(top_3_indices)

[[ 2  9  5]
 [ 9 14 17]
 [16 19  8]]
row-wise normalization [[-3.33333333 -4.33333333 -9.33333333]
 [ 3.66666667  0.66666667  2.66666667]
 [10.66666667  5.66666667 -6.33333333]]
[[[59 64 34 62 -1]
  [-1 52 97 46  7]
  [-1 -1 -1 16 -1]
  [41 -1 26 -1 11]]

 [[-1 47 -1 41 56]
  [25  1 65 56 -1]
  [ 2 19 88 64 71]
  [61 82 64 25 65]]

 [[22 -1 80 -1 31]
  [-1 23 -1 -1 13]
  [86 -1 83 -1 91]
  [28 17 53 11 73]]]
[(2, 0), (1, 2), (2, 1)]
